[package]
name = "crate_glitch"
version = "0.1.0"
authors = ["blakehawkins"]
edition = "2018"

[dependencies]
glitch-in-the-matrix = { git = "https://github.com/eeeeeta/glitch-in-the-matrix.git", branch = "develop" }
hyper = "0.12.35"
hyper-openssl = "0.7.1"
tokio-core = "0.1.17"
